name: stevenmarx.com
favicon: null
layout_spectrum: 0.22164
typography_spectrum: 0.3369471631012857
title: stevenmarx.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#e66366'
    - '#8fcaff'
    - '#888988'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
