name: stevenmarx.com
favicon: null
layout_spectrum: 0.8648872445337474
typography_spectrum: 0.3369471631012857
title: stevenmarx.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d86f6e'
    - '#000000'
    - '#98df7b'
    - '#ff0000'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
