name: stevenmarx.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86473
title: stevenmarx.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e66466'
    - '#000000'
    - '#7ce4ee'
    - '#00ff00'
    - '#0000ff'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
